#---------------------------------
#---------------------------------
# Configuration file
#---------------------------------
#---------------------------------

#tweeter credentials
ACCESS_TOKEN: 434725028-zkBdv7qsM9GGVw28ZTGQQQ5ceXuHe9mO16GV7YKs
ACCESS_TOKEN_SECRET: DuFnNvA9F9y8Hp6bkkrQM5bYaimQ0HACVl2L7XGOiC8Zk
CONSUMER_KEY: omh3Fc49A45oXsmXWju2fLzv1
CONSUMER_KEY_SECRET: h4Sinp0lQL1ktsAj5iaBgTFljDZtVoPhSiMTzdRR7z3ikIQYc2

#---------------------------------
#---------------------------------

#storage properties
storage_folder: tweets.txt
#storage_folder: '.'

#---------------------------------
#---------------------------------

